### ISSUE TITLE
Province problem

### ISSUE THREAD

**Issue by OmkoBass** [NovelCOVID/node-api#17]
historical(null, CountryName, CountryProvince) will never return info about that province only.

`fetch(`${this.baseURL}/v2/historical/${country}/${province}`).then(json)`

**Comment by OmkoBass** [comment]
Closed? It's still the same.

**Comment by Anish-Shobith** [comment]
I released a new version , have you tried updating and trying ?

**Comment by OmkoBass** [comment]
It's still the same, i even hardcoded some data and it doesn't return only one province.

`return data.historical(null, props.country, props.province);`
`return data.historical(null, 'Canada', 'alberta')`

**Comment by Anish-Shobith** [comment]
```js
const { NovelCovid } = require('./dist/index.js');

const track = new NovelCovid();

(async () => {
	console.log(await track.historical(null, 'canada', 'alberta'));
})();
```
This one works for me ? 
```json
{
  country: 'Canada',
  province: 'alberta',
  timeline: {
    cases: {
      '1/22/20': 0,
      '1/23/20': 0,
      '1/24/20': 0,
      '1/25/20': 0,
      '1/26/20': 0,
      '1/27/20': 0,
      '1/28/20': 0,
      '1/29/20': 0,
      '1/30/20': 0,
      '1/31/20': 0,
      '2/1/20': 0,
      '2/2/20': 0,
      '2/3/20': 0,
      '2/4/20': 0,
      '2/5/20': 0,
      '2/6/20': 0,
      '2/7/20': 0,
      '2/8/20': 0,
      '2/9/20': 0,
      '2/10/20': 0,
      '2/11/20': 0,
      '2/12/20': 0,
      '2/13/20': 0,
      '2/14/20': 0,
      '2/15/20': 0,
      '2/16/20': 0,
      '2/17/20': 0,
      '2/18/20': 0,
      '2/19/20': 0,
      '2/20/20': 0,
      '2/21/20': 0,
      '2/22/20': 0,
      '2/23/20': 0,
      '2/24/20': 0,
      '2/25/20': 0,
      '2/26/20': 0,
      '2/27/20': 0,
      '2/28/20': 0,
      '2/29/20': 0,
      '3/1/20': 0,
      '3/2/20': 0,
      '3/3/20': 0,
      '3/4/20': 0,
      '3/5/20': 0,
      '3/6/20': 1,
      '3/7/20': 2,
      '3/8/20': 4,
      '3/9/20': 7,
      '3/10/20': 7,
      '3/11/20': 19,
      '3/12/20': 19,
      '3/13/20': 29,
      '3/14/20': 29,
      '3/15/20': 39,
      '3/16/20': 56,
      '3/17/20': 74,
      '3/18/20': 97,
      '3/19/20': 119,
      '3/20/20': 146,
      '3/21/20': 195,
      '3/22/20': 259,
      '3/23/20': 301,
      '3/24/20': 359,
      '3/25/20': 358,
      '3/26/20': 486,
      '3/27/20': 542,
      '3/28/20': 542,
      '3/29/20': 621,
      '3/30/20': 661,
      '3/31/20': 690,
      '4/1/20': 754,
      '4/2/20': 969,
      '4/3/20': 969
    },
    deaths: {
      '1/22/20': 0,
      '1/23/20': 0,
      '1/24/20': 0,
      '1/25/20': 0,
      '1/26/20': 0,
      '1/27/20': 0,
      '1/28/20': 0,
      '1/29/20': 0,
      '1/30/20': 0,
      '1/31/20': 0,
      '2/1/20': 0,
      '2/2/20': 0,
      '2/3/20': 0,
      '2/4/20': 0,
      '2/5/20': 0,
      '2/6/20': 0,
      '2/7/20': 0,
      '2/8/20': 0,
      '2/9/20': 0,
      '2/10/20': 0,
      '2/11/20': 0,
      '2/12/20': 0,
      '2/13/20': 0,
      '2/14/20': 0,
      '2/15/20': 0,
      '2/16/20': 0,
      '2/17/20': 0,
      '2/18/20': 0,
      '2/19/20': 0,
      '2/20/20': 0,
      '2/21/20': 0,
      '2/22/20': 0,
      '2/23/20': 0,
      '2/24/20': 0,
      '2/25/20': 0,
      '2/26/20': 0,
      '2/27/20': 0,
      '2/28/20': 0,
      '2/29/20': 0,
      '3/1/20': 0,
      '3/2/20': 0,
      '3/3/20': 0,
      '3/4/20': 0,
      '3/5/20': 0,
      '3/6/20': 0,
      '3/7/20': 0,
      '3/8/20': 0,
      '3/9/20': 0,
      '3/10/20': 0,
      '3/11/20': 0,
      '3/12/20': 0,
      '3/13/20': 0,
      '3/14/20': 0,
      '3/15/20': 0,
      '3/16/20': 0,
      '3/17/20': 0,
      '3/18/20': 0,
      '3/19/20': 0,
      '3/20/20': 1,
      '3/21/20': 1,
      '3/22/20': 1,
      '3/23/20': 1,
      '3/24/20': 1,
      '3/25/20': 2,
      '3/26/20': 2,
      '3/27/20': 2,
      '3/28/20': 2,
      '3/29/20': 2,
      '3/30/20': 3,
      '3/31/20': 8,
      '4/1/20': 9,
      '4/2/20': 13,
      '4/3/20': 13
    },
    recovered: {
      '1/22/20': 0,
      '1/23/20': 0,
      '1/24/20': 0,
      '1/25/20': 0,
      '1/26/20': 0,
      '1/27/20': 0,
      '1/28/20': 0,
      '1/29/20': 0,
      '1/30/20': 0,
      '1/31/20': 0,
      '2/1/20': 0,
      '2/2/20': 0,
      '2/3/20': 0,
      '2/4/20': 0,
      '2/5/20': 0,
      '2/6/20': 0,
      '2/7/20': 0,
      '2/8/20': 0,
      '2/9/20': 0,
      '2/10/20': 0,
      '2/11/20': 0,
      '2/12/20': 0,
      '2/13/20': 0,
      '2/14/20': 0,
      '2/15/20': 0,
      '2/16/20': 0,
      '2/17/20': 0,
      '2/18/20': 0,
      '2/19/20': 0,
      '2/20/20': 0,
      '2/21/20': 0,
      '2/22/20': 0,
      '2/23/20': 0,
      '2/24/20': 0,
      '2/25/20': 0,
      '2/26/20': 0,
      '2/27/20': 0,
      '2/28/20': 0,
      '2/29/20': 0,
      '3/1/20': 0,
      '3/2/20': 0,
      '3/3/20': 0,
      '3/4/20': 0,
      '3/5/20': 0,
      '3/6/20': 0,
      '3/7/20': 0,
      '3/8/20': 0,
      '3/9/20': 0,
      '3/10/20': 0,
      '3/11/20': 0,
      '3/12/20': 0,
      '3/13/20': 0,
      '3/14/20': 0,
      '3/15/20': 0,
      '3/16/20': 0,
      '3/17/20': 0,
      '3/18/20': 0,
      '3/19/20': 0,
      '3/20/20': 0,
      '3/21/20': 0,
      '3/22/20': 0,
      '3/23/20': 0,
      '3/24/20': 0,
      '3/25/20': 0,
      '3/26/20': 0,
      '3/27/20': 0,
      '3/28/20': 0,
      '3/29/20': 0,
      '3/30/20': 0,
      '3/31/20': 0,
      '4/1/20': 0,
      '4/2/20': 0,
      '4/3/20': 0
    }
  }
}
``` here is the output
![image](https://user-images.githubusercontent.com/38991749/78463070-6fec2200-76f6-11ea-8d8f-57b3b2891b82.png)

**Comment by OmkoBass** [comment]
I reinstalled novelcovid and everything works now. Thanks brother.
